version: '3'
services:
  app:
    build: .
    volumes:
      - ./data:/app/data
    command: python src/main.py

  test:
    build: .
    volumes:
      - ./data:/app/data
    command: pytest tests/